project:
  type: website
  output-dir: docs

website:
  title: "Agility Game"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - company-purpose.qmd
      - company-vision.qmd
      - company-mission.qmd
      - company-values.qmd
      - portfolio.qmd
      - programs.qmd
      - plans.qmd
      - product-portfolio.qmd
      - product-vision.qmd
      - business-impact-principles-values.qmd
      - product-mission.qmd
      - goals.qmd
      - objectives.qmd
      - targets.qmd
      - strategies.qmd
      - initiatives-tactics.qmd
      - opportunities.qmd
      - ideas.qmd
      - solutions.qmd
      - epics.qmd
      - features.qmd
      - stories.qmd
      - tasks.qmd
      - operations.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
